// Auto-generated by https://github.com/vladkens/apigen-ts
// Source: ./openapi.json

type Headers = Record<string, string>
export type ApigenHeaders = Headers | ((method: string, path: string) => Headers | Promise<Headers>)

export interface ApigenConfig {
  baseUrl: string
  headers: ApigenHeaders
}

export interface ApigenRequest extends Omit<RequestInit, 'body'> {
  search?: Record<string, unknown>
  body?: unknown
}

export class ApiClient {
  Config: ApigenConfig

  constructor(config?: Partial<ApigenConfig>) {
    this.Config = { baseUrl: '/', headers: {}, ...config }
  }

  async ParseError(rep: Response) {
    try {
      return await rep.json()
    } catch (e) {
      throw rep
    }
  }

  PrepareFetchUrl(path: string): URL {
    let base = this.Config.baseUrl
    if ('location' in globalThis && (base === '' || base.startsWith('/'))) {
      const { location } = globalThis as unknown as { location: { origin: string } }
      base = `${location.origin}${base.endsWith('/') ? base : `/${base}`}`
    }

    return new URL(path, base)
  }

  async Fetch<T>(method: string, path: string, opts: ApigenRequest = {}): Promise<T> {
    const url = this.PrepareFetchUrl(path)

    for (const [k, v] of Object.entries(opts?.search ?? {})) {
      url.searchParams.append(k, Array.isArray(v) ? v.join(',') : (v as string))
    }

    const configHeaders = typeof this.Config.headers === 'function' ? await this.Config.headers(method, path) : this.Config.headers

    const headers = new Headers({ ...configHeaders, ...opts.headers })
    const ct = headers.get('content-type') ?? 'application/json'

    let body: FormData | URLSearchParams | string | undefined = undefined

    if (ct === 'multipart/form-data' || ct === 'application/x-www-form-urlencoded') {
      headers.delete('content-type')
      body = ct === 'multipart/form-data' ? new FormData() : new URLSearchParams()
      for (const [k, v] of Object.entries(opts.body as Record<string, string>)) {
        body.append(k, v)
      }
    }

    if (ct === 'application/json' && typeof opts.body !== 'string') {
      headers.set('content-type', 'application/json')
      body = JSON.stringify(opts.body)
    }

    const credentials = opts.credentials ?? 'include'
    const rep = await fetch(url.toString(), { method, ...opts, headers, body, credentials })
    if (!rep.ok) throw await this.ParseError(rep)

    const rs = await rep.text()
    try {
      return JSON.parse(rs) as T
    } catch (e) {
      return rs as unknown as T
    }
  }

  general = {
    getAvailableTranslations: () => {
      return this.Fetch<AvailableTranslations>('get', '/api/available_translation.json', {})
    },

    getBooksForTranslation: (translation: string) => {
      return this.Fetch<TranslationBooks>('get', `/api/${translation}/books.json`, {})
    },

    getChapterFromTranslation: (translation: string, book: string, chapter: number) => {
      return this.Fetch<TranslationBookChapter>('get', `/api/${translation}/${book}/${chapter}.json`, {})
    },
  }
}

export type AudioLinks = Record<string, string>

export type AvailableTranslations = {
  translations: Translation[]
}

export type ChapterContent = ChapterHeading | ChapterLineBreak | ChapterHebrewSubtitle | ChapterVerse

export type ChapterData = {
  number: number
  content: ChapterContent[]
  footnotes: ChapterFootnote[]
}

export type ChapterFootnote = {
  noteId: number
  text: string
  reference?: {
    chapter?: number
    verse?: number
  } | null
  caller: string | null
}

export type ChapterHeading = {
  type: 'heading'
  content: string[]
}

export type ChapterHebrewSubtitle = {
  type: 'hebrew_subtitle'
  content: (string | FormattedText | VerseFootnoteReference)[]
}

export type ChapterLineBreak = {
  type: 'line_break'
}

export type ChapterVerse = {
  type: 'verse'
  number: number
  content: (string | FormattedText | InlineHeading | InlineLineBreak | VerseFootnoteReference)[]
}

export type FormattedText = {
  text: string
  poem?: number | null
  wordsOfJesus?: boolean | null
}

export type InlineHeading = {
  heading: string
}

export type InlineLineBreak = {
  lineBreak: boolean
}

export type Translation = {
  id: string
  name: string
  englishName: string
  website: string
  licenseUrl: string
  shortName: string
  language: string
  languageName?: string | null
  languageEnglishName?: string | null
  textDirection: 'ltr' | 'rtl'
  availableFormats: ('json' | 'usfm')[]
  listOfBooksApiLink: string
  numberOfBooks: number
  totalNumberOfChapters: number
  totalNumberOfVerses: number
  numberOfApocryphalBooks?: number | null
  totalNumberOfApocryphalChapters?: number | null
  totalNumberOfApocryphalVerses?: number | null
}

export type TranslationBook = {
  id: string
  translationId: string
  name: string
  commonName: string
  title?: string | null
  order: number
  numberOfChapters: number
  firstChapterApiLink: string
  lastChapterApiLink: string
  totalNumberOfVerses: number
  isApocryphal?: boolean | null
}

export type TranslationBookChapter = {
  translation: Translation
  book: TranslationBook
  thisChapterApiLink: string
  thisChapterAudioLinks: AudioLinks
  nextChapterApiLink?: string | null
  nextChapterAudioLinks?: AudioLinks | null
  previousChapterApiLink?: string | null
  previousChapterAudioLinks?: AudioLinks | null
  numberOfVerses: number
  chapter: ChapterData
}

export type TranslationBooks = {
  translation: Translation
  books: TranslationBook[]
}

export type VerseFootnoteReference = {
  noteId: number
}
